### ISSUE TITLE
App crashes immediately

### ISSUE THREAD

**Issue by Salvoxia** [armlesswunder/d2rCloneTrackerAndroid#1]
Hi,

Thank you for developing this app!
I installed it from the Play Store, but have been testing your Github releases from the first release on.
For me, the app crashes immediately after start. I can see the app's logo for a split second, then it's gone.
I'm on a Samsung Galaxy S20 with Android 12.
What can I do to provide debug information (logs of some sort)?

Best Regards,
Salvoxia

**Comment by armlesswunder** [comment]
Hello, I fixed the android 12 crash in the latest version (.6) please
download from github or wait for the update to appear in play store (could
take up to a day) please let me know if this works for you, thanks!

**Comment by armlesswunder** [comment]
The patch is now live.

**Comment by armlesswunder** [comment]
I have one report that the app works for Android 12 now. I'll close this out in 24 hours if no response.

**Comment by Salvoxia** [comment]
Yes, version 0.6 works like a charm! Thank you!
