### ISSUE TITLE
How to activate the Performance mode？？

### ISSUE THREAD

**Issue by cineph** [armlesswunder/d2rCloneTrackerAndroid#6]
Can't find the option,thx～
![Screenshot_20220605-080124](https://user-images.githubusercontent.com/103133024/172030913-6285f440-58ad-4d9b-b36f-c2aa34a6413e.jpg)

**Comment by armlesswunder** [comment]
Hello, please update to the latest version via play store. I suppose I forgot to upload the latest version here 😅. Will upload 1.4 here soon.

**Comment by armlesswunder** [comment]
https://github.com/armlesswunder/d2rCloneTrackerAndroid/releases/tag/1.4

**Comment by cineph** [comment]
> Hello, please update to the latest version via play store. I suppose I forgot to upload the latest version here 😅. Will upload 1.4 here soon.

Thank you for your working
I had checked the play store before, it's weird that it didn't remind me to update，so I reinstalled it and it's 1.4 now.
One more question,  where can I set the gs value？

**Comment by armlesswunder** [comment]
Gs value isn't something you update. Gs means greatest status based on your preferences. So if you have a lost of statuses like 1, 2, 3 , 2, 1, 1 then 3 is the greatest status. Hope that helps.

**Comment by cineph** [comment]
> No problem. Gs value isn't something you update. Gs means greatest status based on your preferences. So if you have a lost of statuses like 1, 2, 3 , 2, 1, 1 then 3 is the greatest status. Hope that helps.

Now I got it，again thanku very much～～
